package org.jact.ast;

public enum NodeType {
  NODE_DSL_PROGRAM,
  NODE_PROJECT,
  NODE_COMPILER,
  NODE_SOURCES,
  NODE_SOURCE,
  NODE_INCLUDES,
  NODE_INCLUDE,
  NODE_OUTPUT,
  NODE_TARGET,
  NODE_CFLAGS,
  NODE_CFLAG,
  NODE_LDFLAGS,
  NODE_LDFLAG,
  NODE_LINKER,
  NODE_LINK,
}
