package org.jact.lexer;

public enum TokenType {
  TYPE_INVALID,
  TYPE_IDENT,
  TYPE_OPEN_CBRACE,
  TYPE_CLOSE_CBRACE,
  TYPE_PROJECT,
  TYPE_STRING,
  TYPE_COMPILER,
  TYPE_SOURCES,
  TYPE_INCLUDES,
  TYPE_OUTPUT,
  TYPE_TARGET,
  TYPE_CFLAGS,
  TYPE_LDFLAGS,
  TYPE_EOF,
}
